export const PYTHON_WRAPPER_CODE = [
  "import sys",
  "import ast",
  "import json",
  "import builtins",
  "",
  "# --- Configuration & Limits ---",
  "MAX_STEPS = 1500",
  "MAX_STDOUT = 20000",
  "MAX_DEPTH = 3",
  "MAX_ITEMS = 50",
  "MAX_STR_LEN = 200",
  "",
  "# --- AST Validation ---",
  "class SecurityScanner(ast.NodeVisitor):",
  "    def visit_Import(self, node):",
  "        raise SecurityError('Imports are not allowed in this environment.')",
  "    ",
  "    def visit_ImportFrom(self, node):",
  "        raise SecurityError('Imports are not allowed in this environment.')",
  "        ",
  "    def visit_Call(self, node):",
  "        if isinstance(node.func, ast.Name) and node.func.id in ['eval', 'exec', 'open', 'compile', 'input', '__import__', 'globals', 'locals', 'vars', 'breakpoint']:",
  "            raise SecurityError(f'Function \\'{node.func.id}\\' is not allowed.')",
  "        self.generic_visit(node)",
  "",
  "    def visit_Attribute(self, node):",
  "        if node.attr.startswith('__'):",
  "            raise SecurityError(f'Access to dunder attributes is not allowed.')",
  "        self.generic_visit(node)",
  "",
  "class SecurityError(Exception):",
  "    pass",
  "",
  "def validate_code(code: str):",
  "    try:",
  "        tree = ast.parse(code)",
  "        scanner = SecurityScanner()",
  "        scanner.visit(tree)",
  "    except SyntaxError as e:",
  "        raise e",
  "",
  "# --- Serializer ---",
  "def safe_serialize(obj, depth=0):",
  "    if depth > MAX_DEPTH:",
  "        return {'type': 'truncated', 'value': 'Maximum nesting depth reached'}",
  "    ",
  "    if obj is None:",
  "        return {'type': 'null', 'value': None}",
  "    elif isinstance(obj, bool):",
  "        return {'type': 'bool', 'value': obj}",
  "    elif isinstance(obj, int):",
  "        return {'type': 'int', 'value': obj}",
  "    elif isinstance(obj, float):",
  "        return {'type': 'float', 'value': obj}",
  "    elif isinstance(obj, str):",
  "        if len(obj) > MAX_STR_LEN:",
  "            return {'type': 'str', 'value': obj[:MAX_STR_LEN] + '... (truncated)'}",
  "        return {'type': 'str', 'value': obj}",
  "    elif isinstance(obj, list):",
  "        if len(obj) > MAX_ITEMS:",
  "            return {'type': 'list', 'value': [safe_serialize(x, depth + 1) for x in obj[:MAX_ITEMS]] + [{'type': 'truncated', 'value': '... more'}]}",
  "        return {'type': 'list', 'value': [safe_serialize(x, depth + 1) for x in obj]}",
  "    elif isinstance(obj, tuple):",
  "        if len(obj) > MAX_ITEMS:",
  "            return {'type': 'tuple', 'value': [safe_serialize(x, depth + 1) for x in obj[:MAX_ITEMS]] + [{'type': 'truncated', 'value': '... more'}]}",
  "        return {'type': 'tuple', 'value': [safe_serialize(x, depth + 1) for x in obj]}",
  "    elif isinstance(obj, set):",
  "        lst = list(obj)",
  "        if len(lst) > MAX_ITEMS:",
  "            return {'type': 'set', 'value': [safe_serialize(x, depth + 1) for x in lst[:MAX_ITEMS]] + [{'type': 'truncated', 'value': '... more'}]}",
  "        return {'type': 'set', 'value': [safe_serialize(x, depth + 1) for x in lst]}",
  "    elif isinstance(obj, dict):",
  "        if len(obj) > MAX_ITEMS:",
  "            pairs = list(obj.items())[:MAX_ITEMS]",
  "            res = {str(k): safe_serialize(v, depth + 1) for k, v in pairs}",
  "            res['__truncated__'] = {'type': 'truncated', 'value': '... more keys'}",
  "            return {'type': 'dict', 'value': res}",
  "        return {'type': 'dict', 'value': {str(k): safe_serialize(v, depth + 1) for k, v in obj.items()}}",
  "    else:",
  "        rep = repr(obj)",
  "        if len(rep) > MAX_STR_LEN:",
  "            rep = rep[:MAX_STR_LEN] + '...'",
  "        return {'type': 'unsupported', 'value': rep}",
  "",
  "# --- Execution Core ---",
  "def run_logiclab(user_code: str):",
  "    try:",
  "        validate_code(user_code)",
  "    except Exception as e:",
  "        name = type(e).__name__",
  "        msg = str(e)",
  "        line = getattr(e, 'lineno', 1)",
  "        return json.dumps({",
  "            'steps': [],",
  "            'stdout': '',",
  "            'error': {'name': name, 'message': msg, 'line': line},",
  "            'durationMs': 0,",
  "            'truncated': False",
  "        })",
  "    ",
  "    compiled_code = compile(user_code, '<logiclab-user-code>', 'exec')",
  "    ",
  "    trace_steps = []",
  "    stdout_buffer = []",
  "    ",
  "    class CaptureStdout:",
  "        def write(self, text):",
  "            stdout_buffer.append(text)",
  "        def flush(self):",
  "            pass",
  "",
  "    original_stdout = sys.stdout",
  "    sys.stdout = CaptureStdout()",
  "    ",
  "    safe_builtins = {}",
  "    allowed_builtins = ['print', 'range', 'len', 'enumerate', 'zip', 'min', 'max', 'sum', 'abs', 'round', 'sorted', 'reversed', 'all', 'any', 'type', 'int', 'float', 'str', 'bool', 'list', 'dict', 'tuple', 'set', 'Exception', 'ValueError', 'TypeError', 'IndexError', 'KeyError', 'ZeroDivisionError', 'AssertionError']",
  "    for name in allowed_builtins:",
  "        if hasattr(builtins, name):",
  "            safe_builtins[name] = getattr(builtins, name)",
  "            ",
  "    exec_globals = {'__builtins__': safe_builtins}",
  "    exec_locals = {}",
  "    ",
  "    step_count = 0",
  "    truncation_reason = None",
  "    ",
  "    def trace_calls(frame, event, arg):",
  "        nonlocal step_count, truncation_reason",
  "        ",
  "        if frame.f_code.co_filename != '<logiclab-user-code>':",
  "            if event == 'call':",
  "                return None",
  "            return trace_calls",
  "            ",
  "        if step_count >= MAX_STEPS:",
  "            truncation_reason = 'Maximum step count reached'",
  "            sys.settrace(None)",
  "            raise RuntimeError(truncation_reason)",
  "            ",
  "        current_stdout = ''.join(stdout_buffer)",
  "        if len(current_stdout) > MAX_STDOUT:",
  "            truncation_reason = 'Maximum output length reached'",
  "            sys.settrace(None)",
  "            raise RuntimeError(truncation_reason)",
  "            ",
  "        stack_frames = []",
  "        f = frame",
  "        while f:",
  "            if f.f_code.co_filename == '<logiclab-user-code>':",
  "                f_locals = {}",
  "                for k, v in f.f_locals.items():",
  "                    if not k.startswith('__'):",
  "                        f_locals[k] = safe_serialize(v)",
  "                stack_frames.append({",
  "                    'functionName': f.f_code.co_name,",
  "                    'locals': f_locals,",
  "                    'line': f.f_lineno",
  "                })",
  "            f = f.f_back",
  "        stack_frames.reverse()",
  "        depth = len(stack_frames)",
  "            ",
  "        safe_locals = {}",
  "        for k, v in frame.f_locals.items():",
  "            if not k.startswith('__'):",
  "                safe_locals[k] = safe_serialize(v)",
  "                ",
  "        step_count += 1",
  "        step = {",
  "            'id': step_count,",
  "            'event': event,",
  "            'line': frame.f_lineno,",
  "            'functionName': frame.f_code.co_name,",
  "            'callDepth': depth,",
  "            'locals': safe_locals,",
  "            'stdout': current_stdout,",
  "            'stdoutDelta': '',",
  "            'stack': stack_frames",
  "        }",
  "        ",
  "        if event == 'return':",
  "            step['returnValue'] = safe_serialize(arg)",
  "        elif event == 'exception':",
  "            exc_type, exc_value, exc_traceback = arg",
  "            step['exception'] = {",
  "                'name': exc_type.__name__,",
  "                'message': str(exc_value)",
  "            }",
  "            ",
  "        trace_steps.append(step)",
  "        return trace_calls",
  "",
  "    error_result = None",
  "    ",
  "    import time",
  "    start_time = time.time()",
  "    ",
  "    try:",
  "        sys.settrace(trace_calls)",
  "        exec(compiled_code, exec_globals, exec_globals)",
  "    except Exception as e:",
  "        if truncation_reason and str(e) == truncation_reason:",
  "            pass",
  "        else:",
  "            name = type(e).__name__",
  "            msg = str(e)",
  "            ",
  "            tb = sys.exc_info()[2]",
  "            line = 1",
  "            while tb:",
  "                if tb.tb_frame.f_code.co_filename == '<logiclab-user-code>':",
  "                    line = tb.tb_lineno",
  "                tb = tb.tb_next",
  "                ",
  "            error_result = {'name': name, 'message': msg, 'line': line}",
  "    finally:",
  "        sys.settrace(None)",
  "        sys.stdout = original_stdout",
  "        ",
  "    durationMs = int((time.time() - start_time) * 1000)",
  "    ",
  "    final_stdout = ''.join(stdout_buffer)",
  "    prev_stdout = ''",
  "    for step in trace_steps:",
  "        step['stdoutDelta'] = step['stdout'][len(prev_stdout):]",
  "        prev_stdout = step['stdout']",
  "        ",
  "    return json.dumps({",
  "        'steps': trace_steps,",
  "        'stdout': final_stdout[:MAX_STDOUT],",
  "        'error': error_result,",
  "        'durationMs': durationMs,",
  "        'truncated': truncation_reason is not None,",
  "        'truncationReason': truncation_reason",
  "    })",
  ""
].join("\n");
